// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// codegen_impl
List codegen_impl(RObject exp, const std::string& fname, Environment env);
RcppExport SEXP rosa_codegen_impl(SEXP expSEXP, SEXP fnameSEXP, SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type exp(expSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< Environment >::type env(envSEXP);
    rcpp_result_gen = Rcpp::wrap(codegen_impl(exp, fname, env));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"rosa_codegen_impl", (DL_FUNC) &rosa_codegen_impl, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rosa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
