# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
codegen_impl <- function(exp, fname, env) {
    .Call('rosa_codegen_impl', PACKAGE = 'rosa', exp, fname, env)
}

#' @export
test <- function() {
    .Call('rosa_test', PACKAGE = 'rosa')
}

