# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
codegen <- function(exp, env) {
    invisible(.Call('rosa_codegen', PACKAGE = 'rosa', exp, env))
}

#' @export
PrintExp <- function(x) {
    invisible(.Call('rosa_PrintExp', PACKAGE = 'rosa', x))
}

